Rename_Vars <- function(input){

  #define names to be filtered from table-names
  # trait_nms <- c("LeArea","SSD","SLA","LeC","LeN_","LeP","PlantHeight","SeedMass","SeLen","LeNArea",
  #                 "LeNP","Led15N","SenbU","LeFMass","ConduitDens","DispULen","VesLen")

  transl_s <-matrix(NA,ncol=2,nrow=length(input)) 
  transl_s[,1] <- input#c(SG_n,OLM_n,climate_fcts)
  transl_s_sd <- transl_s
  transl_c <- transl_s # climate variables
  transl_c_sd <- transl_s # climate variables
  transl_t <- transl_s # trait names
  transl_t_sd<- transl_s # trait names but sd
  transl_a <- transl_s # 
  transl_a1 <- transl_s # 
  transl_a2 <- transl_s # 
  transl_a3 <- transl_s # 
  transl_d <- transl_s #
  
  

 # traits 1/4 
  transl_t[which(transl_t[,1]%in%"X4"),2] <- "SSD" 
  transl_t[which(transl_t[,1]%in%"X11"),2] <- "SLA" 
  transl_t[which(transl_t[,1]%in%"X13"),2] <- "LeC"
  transl_t[which(transl_t[,1]%in%"X14"),2] <- "LeN" 
  transl_t[which(transl_t[,1]%in%"X15"),2] <- "LeP" 
  transl_t[which(transl_t[,1]%in%"X18"),2] <- "PlantHeight" 
  transl_t[which(transl_t[,1]%in%"X26"),2] <- "SeedMass" 
  transl_t[which(transl_t[,1]%in%"X27"),2] <- "SeLen" 
  transl_t[which(transl_t[,1]%in%"X50"),2] <- "LeNArea" 
  transl_t[which(transl_t[,1]%in%"X56"),2] <- "LeNP" 
  transl_t[which(transl_t[,1]%in%"X78"),2] <- "Led15N" 
  transl_t[which(transl_t[,1]%in%"X138"),2] <- "SenbU" 
  transl_t[which(transl_t[,1]%in%"X163"),2] <- "LeFMass" 
  transl_t[which(transl_t[,1]%in%"X169"),2] <- "ConduitDens" 
  transl_t[which(transl_t[,1]%in%"X237"),2] <- "DispULen" 
  transl_t[which(transl_t[,1]%in%"X282"),2] <- "VesLen" 


  
  #traits 2/4
  transl_t[which(transl_t[,1]%in%"LeArea"),2] <- "Leaf Area" 
  transl_t[which(transl_t[,1]%in%"Led15N"),2] <- "Delta 15 N"
  transl_t[which(transl_t[,1]%in%"LeNArea"),2] <- "Leaf N per Area"
  transl_t[which(transl_t[,1]%in%"LeNP"),2] <- "Leaf N:P ratio"
  transl_t[which(transl_t[,1]%in%"LeC"),2] <- "Leaf C"
  transl_t[which(transl_t[,1]%in%"LeP"),2] <- "Leaf P" 
  transl_t[which(transl_t[,1]%in%"LeN"),2] <- "Leaf N" 
  transl_t[which(transl_t[,1]%in%"SLA"),2] <- "SLA" 
  transl_t[which(transl_t[,1]%in%"ConduitDens"),2] <- "Conduit density" 
  transl_t[which(transl_t[,1]%in%"LeFMass"),2] <- "Leaf fresh mass" 
  transl_t[which(transl_t[,1]%in%"SenbU"),2] <- "Seeds per Reprod U" 
  transl_t[which(transl_t[,1]%in%"PlantHeight"),2] <- "Height" 
  transl_t[which(transl_t[,1]%in%"SeLen"),2] <- "Seed length" 
  transl_t[which(transl_t[,1]%in%"VesLen"),2] <- "Vessel el. length" 
  transl_t[which(transl_t[,1]%in%"DispULen"),2] <- "Dispersal U length" 
  transl_t[which(transl_t[,1]%in%"SeedMass"),2] <- "Seed mass"  
  transl_t[which(transl_t[,1]%in%"SSD"),2] <- "Stem Density" 

  #traits 3/4
  transl_t[which(transl_t[,1]%in%"Leaf area"),2] <- "LeArea" 
  transl_t[which(transl_t[,1]%in%"Stem dry mass per stem fresh volume (stem specific density, SSD)"),2] <- "SSD" 
  transl_t[which(transl_t[,1]%in%"Leaf area per leaf dry mass (specific leaf area, SLA)"),2] <- "SLA" 
  transl_t[which(transl_t[,1]%in%"Leaf carbon (C) content per leaf dry mass"),2] <- "LeC"
  transl_t[which(transl_t[,1]%in%"Leaf nitrogen (N) content per leaf dry mass"),2] <- "LeN" 
  transl_t[which(transl_t[,1]%in%"Leaf phosphorus (P) content per leaf dry mass"),2] <- "LeP" 
  transl_t[which(transl_t[,1]%in%"Plant height, vegetative"),2] <- "PlantHeight" 
  transl_t[which(transl_t[,1]%in%"Seed dry mass"),2] <- "SeedMass" 
  transl_t[which(transl_t[,1]%in%"Plant height, reproductive"),2] <- "HeightRep" 
  transl_t[which(transl_t[,1]%in%"Rooting depth"),2] <- "RootDepth" 
  transl_t[which(transl_t[,1]%in%"Leaf carbon/nitrogen (C/N) ratio"),2] <- "LeCN" 
  transl_t[which(transl_t[,1]%in%"Leaf nitrogen/phosphorus (N/P) ratio"),2] <- "LeNP" 
  transl_t[which(transl_t[,1]%in%"Leaf nitrogen (N) isotope signature (delta 15N)"),2] <- "Led15N" 
  transl_t[which(transl_t[,1]%in%"Leaf dry mass per leaf fresh mass (Leaf dry matter content, LDMC)"),2] <- "LDMC" 
  transl_t[which(transl_t[,1]%in%"Leaf fresh mass"),2] <- "LeFMass" 
  transl_t[which(transl_t[,1]%in%"Leaf dry mass"),2] <- "LeMass" 
  transl_t[which(transl_t[,1]%in%"Leaf carbon (C) isotope discrimination (delta 13C)"),2] <- "LeCd13" 
  transl_t[which(transl_t[,1]%in%"Stem diameter"),2] <- "StemDiam" 
  
    
  # traits 4/4  as in TRY data base
  transl_t[which(transl_t[,1]%in%"X1"),2] <- "LeArea" 
  transl_t[which(transl_t[,1]%in%"X6"),2] <- "RootDepth" 
  transl_t[which(transl_t[,1]%in%"X9"),2] <- "Root/shoot ratio" 
  transl_t[which(transl_t[,1]%in%"X12"),2] <- "Leaf lifespan (longevity)" 
  transl_t[which(transl_t[,1]%in%"X21"),2] <- "StemDiam" 
  transl_t[which(transl_t[,1]%in%"X24"),2] <- "Bark thickness" 
  transl_t[which(transl_t[,1]%in%"X40"),2] <- "Leaf photosynthesis rate per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X41"),2] <- "Leaf respiration rate in the dark per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X44"),2] <- "Leaf potassium (K) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X45"),2] <- "Stomata conductance per leaf area" 
  transl_t[which(transl_t[,1]%in%"X46"),2] <- "Leaf thickness" 
  transl_t[which(transl_t[,1]%in%"X47"),2] <- "Leaf dry mass per leaf fresh mass (leaf dry matter content, LDMC)" 
  transl_t[which(transl_t[,1]%in%"X48"),2] <- "Leaf density (leaf tissue density, leaf dry mass per leaf volume)"  
  transl_t[which(transl_t[,1]%in%"X49"),2] <- "Leaf photosynthesis: intercellular CO2 concentration"  
  transl_t[which(transl_t[,1]%in%"X51"),2] <- "Leaf phosphorus (P) content per leaf area"  
  transl_t[which(transl_t[,1]%in%"X53"),2] <- "Leaf photosynthesis rate per leaf area"  
  transl_t[which(transl_t[,1]%in%"X54"),2] <- "Leaf respiration rate in the dark per leaf area"  
  transl_t[which(transl_t[,1]%in%"X55"),2] <- "Leaf dry mass (single leaf)"#new  
  transl_t[which(transl_t[,1]%in%"X57"),2] <- "Leaf nitrogen (N) content per leaf"  
  transl_t[which(transl_t[,1]%in%"X59"),2] <- "Plant lifespan (longevity)"  
  transl_t[which(transl_t[,1]%in%"X63"),2] <- "Stomata density"  
  transl_t[which(transl_t[,1]%in%"X66"),2] <- "Seed terminal velocity"  
  transl_t[which(transl_t[,1]%in%"X70"),2] <- "Litter nitrogen (N) content per litter dry mass"  
  transl_t[which(transl_t[,1]%in%"X77"),2] <- "Plant growth rate relative (plant relative growth rate, RGR)"  
  transl_t[which(transl_t[,1]%in%"X78"),2] <- "Leaf nitrogen (N) isotope signature (delta 15N)"  
  transl_t[which(transl_t[,1]%in%"X79"),2] <- "Leaf minus soil nitrogen (N) isotope signature (leaf delta 15N minus soil delta 15N)"  
  transl_t[which(transl_t[,1]%in%"X80"),2] <- "Root nitrogen (N) content per root dry mass"  
  transl_t[which(transl_t[,1]%in%"X82"),2] <- "Root tissue density (root dry mass per root volume)"  
  transl_t[which(transl_t[,1]%in%"X85"),2] <- "Leaf soluble components content per leaf dry mass"  
  transl_t[which(transl_t[,1]%in%"X87"),2] <- "Leaf lignin content per leaf dry mass"  
  transl_t[which(transl_t[,1]%in%"X92"),2] <- "Leaf cellulose content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X94"),2] <- "Leaf hemi-cellulose content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X95"),2] <- "Seed germination rate (germination efficiency)" 
  transl_t[which(transl_t[,1]%in%"X96"),2] <- "Seed oil content per seed mass" 
  transl_t[which(transl_t[,1]%in%"X97"),2] <- "Seed protein content per seed mass" 
  transl_t[which(transl_t[,1]%in%"X106"),2] <- "Stomata conductance per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X110"),2] <- "Plant biomass and allometry: Leaf dry mass per plant dry mass (leaf weight ratio, LWR)" 
  transl_t[which(transl_t[,1]%in%"X111"),2] <- "Leaf transpiration rate per leaf area" 
  transl_t[which(transl_t[,1]%in%"X125"),2] <- "Leaf area per leaf fresh mass (specific leaf area (SLA or 1/LMA) based on leaf fresh mass)" 
  transl_t[which(transl_t[,1]%in%"X128"),2] <- "Plant biomass and allometry: Stem dry mass per plant" 
  transl_t[which(transl_t[,1]%in%"X129"),2] <- "Plant biomass and allometry: Leaf dry mass per plant" 
  transl_t[which(transl_t[,1]%in%"X131"),2] <- "Plant biomass and allometry: Seed number per plant" 
  transl_t[which(transl_t[,1]%in%"X134"),2] <- "Leaf photosynthesis rate per leaf transpiration (photosynthetic water use effinciency: WUE)" 
  transl_t[which(transl_t[,1]%in%"X138"),2] <- "Seed number per reproducton unit" 
  transl_t[which(transl_t[,1]%in%"X142"),2] <- "Leaf perimeter" 
  transl_t[which(transl_t[,1]%in%"X143"),2] <- "Leaf petiole length" 
  transl_t[which(transl_t[,1]%in%"X144"),2] <- "Leaf length" 
  transl_t[which(transl_t[,1]%in%"X145"),2] <- "Leaf width" 
  transl_t[which(transl_t[,1]%in%"X146"),2] <- "LeCN" # abbrev
  transl_t[which(transl_t[,1]%in%"X147"),2] <- "Leaf phenols content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X163"),2] <- "Leaf fresh mass"   
  transl_t[which(transl_t[,1]%in%"X169"),2] <- "Stem conduit density (vessels and tracheids)"   
  transl_t[which(transl_t[,1]%in%"X170"),2] <- "Stem conduit cross-sectional area (vessels and tracheids)" 
  transl_t[which(transl_t[,1]%in%"X172"),2] <- "Stem conduit lumen cross-sectional area (vessels and tracheids) per stem sapwood cross-sectional are" 
  transl_t[which(transl_t[,1]%in%"X185"),2] <- "Leaf photosynthesis carboxylation capacity (Vcmax) per leaf dry mass (Farquhar model)" 
  transl_t[which(transl_t[,1]%in%"X186"),2] <- "Leaf photosynthesis carboxylation capacity (Vcmax) per leaf area (Farquhar model)" 
  transl_t[which(transl_t[,1]%in%"X200"),2] <- "Species occurrence range: number of floristic zones" 
  transl_t[which(transl_t[,1]%in%"X221"),2] <- "Species genotype: chromosome base number" 
  transl_t[which(transl_t[,1]%in%"X223"),2] <- "Species genotype: chromosome number" 
  transl_t[which(transl_t[,1]%in%"X224"),2] <- "Species genotype: chromosome cDNA content" 
  transl_t[which(transl_t[,1]%in%"X233"),2] <- "Dispersal unit dry mass" 
  transl_t[which(transl_t[,1]%in%"X235"),2] <- "Dispersal unit thickness " 
  transl_t[which(transl_t[,1]%in%"X236"),2] <- "Dispersal unit width" 
  transl_t[which(transl_t[,1]%in%"X237"),2] <- "Dispersal unit length" 
  transl_t[which(transl_t[,1]%in%"X238"),2] <- "Seed thickness" 
  transl_t[which(transl_t[,1]%in%"X239"),2] <- "Seed width" 
  transl_t[which(transl_t[,1]%in%"X249"),2] <- "Leaf aluminium (Al) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X250"),2] <- "Leaf boron (B) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X251"),2] <- "Leaf barium (Ba) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X252"),2] <- "Leaf calcium (Ca) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X253"),2] <- "Leaf chlorophyll fluorescence" 
  transl_t[which(transl_t[,1]%in%"X254"),2] <- "Leaf chromium (Cr) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X255"),2] <- "Leaf copper (Cu) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X256"),2] <- "Leaf iron (Fe) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X257"),2] <- "Leaf magnesium (Mg) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X258"),2] <- "Leaf manganese (Mn) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X259"),2] <- "Leaf molybdenum (Mo) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X260"),2] <- "Leaf sodium (Na) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X261"),2] <- "Leaf nickel (Ni) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X262"),2] <- "Leaf sulfur (S) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X264"),2] <- "Leaf silicon (Si) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X265"),2] <- "Leaf strontium (Sr) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X266"),2] <- "Leaf titanium (Ti) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X268"),2] <- "Leaf zinc (Zn) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X269"),2] <- "Leaf photosynthesis electron transport capacity (Jmax) per leaf area (Farquhar model)" 
  transl_t[which(transl_t[,1]%in%"X270"),2] <- "Leaf photosynthesis electron transport capacity (Jmax) per leaf dry mass (Farquhar model)" 
  transl_t[which(transl_t[,1]%in%"X281"),2] <- "Stem conduit diameter (vessels, tracheids)" 
  transl_t[which(transl_t[,1]%in%"X282"),2] <- "Wood vessel element length; stem conduit (vessel and tracheids) element length" 
  transl_t[which(transl_t[,1]%in%"X289"),2] <- "Wood fiber lengths" 
  transl_t[which(transl_t[,1]%in%"X297"),2] <- "Wood rays per millimetre" 
  transl_t[which(transl_t[,1]%in%"X324"),2] <- "Crown (canopy) length: diameter along the longest axis" 
  transl_t[which(transl_t[,1]%in%"X325"),2] <- "Crown (canopy) width" 
  transl_t[which(transl_t[,1]%in%"X333"),2] <- "Leaf ash content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X336"),2] <- "Seed number per ramet" 
  transl_t[which(transl_t[,1]%in%"X339"),2] <- "Shoot nitrogen (N) content per shoot dry mass" 
  transl_t[which(transl_t[,1]%in%"X340"),2] <- "Shoot phosphorus (P) content per shoot dry mass" 
  transl_t[which(transl_t[,1]%in%"X351"),2] <- "Seed number per dispersal unit" 
  transl_t[which(transl_t[,1]%in%"X353"),2] <- "Seed germination temperature" 
  transl_t[which(transl_t[,1]%in%"X363"),2] <- "Plant biomass and allometry: Root dry mass per plant" 
  transl_t[which(transl_t[,1]%in%"X364"),2] <- "Plant height of lowest branch" 
  transl_t[which(transl_t[,1]%in%"X406"),2] <- "Stem nitrogen (N) content per stem dry mass" 
  transl_t[which(transl_t[,1]%in%"X407"),2] <- "Stem carbon (C) content per stem dry mass" 
  transl_t[which(transl_t[,1]%in%"X410"),2] <- "Leaf area per plant" 
  transl_t[which(transl_t[,1]%in%"X413"),2] <- "Leaf chlorophyll content per leaf area" 
  transl_t[which(transl_t[,1]%in%"X420"),2] <- "Wood: bars per vessel perforation plate" 
  transl_t[which(transl_t[,1]%in%"X449"),2] <- "Plant biomass and allometry: Branch dry mass (alive, dead) per plant" 
  transl_t[which(transl_t[,1]%in%"X511"),2] <- "Plant number of branches per tree" 
  transl_t[which(transl_t[,1]%in%"X514"),2] <- "Root respiration rate per root dry mass" 
  transl_t[which(transl_t[,1]%in%"X520"),2] <- "Stem respiration rate per stem surface area" 
  transl_t[which(transl_t[,1]%in%"X539"),2] <- "Leaf chlorine (Cl) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X540"),2] <- "Leaf scandium (Sc) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X542"),2] <- "Leaf bromine (Br) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X543"),2] <- "Leaf rubidium (Rb) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X546"),2] <- "Leaf antimony (Sb) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X547"),2] <- "Leaf caesium (Cs) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X548"),2] <- "Leaf lanthanum (La) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X549"),2] <- "Leaf cerium (Ce) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X551"),2] <- "Leaf samarium (Sm) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X552"),2] <- "Leaf europium (Eu) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X570"),2] <- "Leaf carbon (C) content per leaf area" 
  transl_t[which(transl_t[,1]%in%"X616"),2] <- "Stem phosphorus (P) content per stem dry mass" 
  transl_t[which(transl_t[,1]%in%"X753"),2] <- "Leaf chlorophyll fluorescence" 
  transl_t[which(transl_t[,1]%in%"X759"),2] <- "Leaflet number per leaf" 
  transl_t[which(transl_t[,1]%in%"X777"),2] <- "Leaf petiole fresh mass" 
  transl_t[which(transl_t[,1]%in%"X778"),2] <- "Leaf petiole dry mass" 
  transl_t[which(transl_t[,1]%in%"X779"),2] <- "Leaf petiole diameter" 
  transl_t[which(transl_t[,1]%in%"X784"),2] <- "unknown_trait" 
  transl_t[which(transl_t[,1]%in%"X861"),2] <- "Branch number of secondary branches at first branching" 
  transl_t[which(transl_t[,1]%in%"X862"),2] <- "Branch number per height along the shoot axis" 
  transl_t[which(transl_t[,1]%in%"X888"),2] <- "Cone (strobilus) dry mass" 
  transl_t[which(transl_t[,1]%in%"X939"),2] <- "Leaf isoprene emission rate per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X940"),2] <- "Leaf length excluding petiole (leaf lamina length)" 
  transl_t[which(transl_t[,1]%in%"X967"),2] <- "Leaf volatile organic carbon (VOC): monoterpene emission rate per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X968"),2] <- "Leaf nitrogen (N) fraction in ammonium (NH4+)" 
  transl_t[which(transl_t[,1]%in%"X969"),2] <- "Leaf nitrogen (N) fraction in N2" 
  transl_t[which(transl_t[,1]%in%"X970"),2] <- "Leaf nitrogen (N) fraction in nitrate (NO3-)" 
  transl_t[which(transl_t[,1]%in%"X973"),2] <- "Leaf petiole projected area" 
  transl_t[which(transl_t[,1]%in%"X978"),2] <- "Leaf shrinkage" 
  transl_t[which(transl_t[,1]%in%"X981"),2] <- "Leaf transpiration rate per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X982"),2] <- "Leaf relative water content (leaf water content fresh / leaf water content saturated; RWC)" 
  transl_t[which(transl_t[,1]%in%"X984"),2] <- "Leaf water saturation deficit" 
  transl_t[which(transl_t[,1]%in%"X985"),2] <- "Leaflet length" 
  transl_t[which(transl_t[,1]%in%"X1011"),2] <- "Leaf petiole projected area per petiole dry mass (specific leaf area (SLA) of leaf petiole)" 
  transl_t[which(transl_t[,1]%in%"X1096"),2] <- "Wood (sapwood) specific conductivity (stem specific conductivity)" 
  transl_t[which(transl_t[,1]%in%"X1097"),2] <- "Wood (sapwood) water content" 
  transl_t[which(transl_t[,1]%in%"X1103"),2] <- "Seed number per flower" 
  transl_t[which(transl_t[,1]%in%"X1104"),2] <- "Seed number per inflorescence (total, fertile, infertile)" 
  transl_t[which(transl_t[,1]%in%"X1105"),2] <- "Seed number per square meter" 
  transl_t[which(transl_t[,1]%in%"X1106"),2] <- "Seed number per stem" 
  transl_t[which(transl_t[,1]%in%"X1111"),2] <- "Seedbank density" 
  transl_t[which(transl_t[,1]%in%"X1130"),2] <- "Species environmental indicator value according to Ellenberg: continentality" 
  transl_t[which(transl_t[,1]%in%"X1131"),2] <- "Species environmental indicator value according to Ellenberg: light" 
  transl_t[which(transl_t[,1]%in%"X1132"),2] <- "Species environmental indicator value according to Ellenberg: moisture" 
  transl_t[which(transl_t[,1]%in%"X1133"),2] <- "Species environmental indicator value according to Ellenberg: nitrogen" 
  transl_t[which(transl_t[,1]%in%"X1134"),2] <- "Species environmental indicator value according to Ellenberg: pH " 
  transl_t[which(transl_t[,1]%in%"X1135"),2] <- "Species environmental indicator value according to Ellenberg: salt tolerance" 
  transl_t[which(transl_t[,1]%in%"X1136"),2] <- "Species environmental indicator value according to Ellenberg: temperature" 
  transl_t[which(transl_t[,1]%in%"X1186"),2] <- "Shoot length to first flower" 
  transl_t[which(transl_t[,1]%in%"X1187"),2] <- "Stem longevity" 
  transl_t[which(transl_t[,1]%in%"X1200"),2] <- "Twig diameter" 
  transl_t[which(transl_t[,1]%in%"X1204"),2] <- "Stem dry mass per stem fresh volume (stem specific density, SSD, Wood density) Twigs and branches sm" 
  
  # traits 4/4  as in TRY data base
  transl_t[which(transl_t[,1]%in%"X1"),2] <- "LeArea" 
  transl_t[which(transl_t[,1]%in%"X6"),2] <- "Root rooting depth" 
  transl_t[which(transl_t[,1]%in%"X9"),2] <- "Root/shoot ratio" 
  transl_t[which(transl_t[,1]%in%"X12"),2] <- "Leaf lifespan (longevity)" 
  transl_t[which(transl_t[,1]%in%"X21"),2] <- "Stem diameter" 
  transl_t[which(transl_t[,1]%in%"X24"),2] <- "Bark thickness" 
  transl_t[which(transl_t[,1]%in%"X40"),2] <- "Leaf photosynthesis rate per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X41"),2] <- "Leaf respiration rate in the dark per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X44"),2] <- "Leaf potassium (K) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X45"),2] <- "Stomata conductance per leaf area" 
  transl_t[which(transl_t[,1]%in%"X46"),2] <- "Leaf thickness" 
  transl_t[which(transl_t[,1]%in%"X47"),2] <- "Leaf dry mass per leaf fresh mass (leaf dry matter content, LDMC)" 
  transl_t[which(transl_t[,1]%in%"X48"),2] <- "Leaf density (leaf tissue density, leaf dry mass per leaf volume)"  
  transl_t[which(transl_t[,1]%in%"X49"),2] <- "Leaf photosynthesis: intercellular CO2 concentration"  
  transl_t[which(transl_t[,1]%in%"X51"),2] <- "Leaf phosphorus (P) content per leaf area"  
  transl_t[which(transl_t[,1]%in%"X53"),2] <- "Leaf photosynthesis rate per leaf area"  
  transl_t[which(transl_t[,1]%in%"X54"),2] <- "Leaf respiration rate in the dark per leaf area"  
  transl_t[which(transl_t[,1]%in%"X55"),2] <- "Leaf dry mass (single leaf)"  
  transl_t[which(transl_t[,1]%in%"X57"),2] <- "Leaf nitrogen (N) content per leaf"  
  transl_t[which(transl_t[,1]%in%"X59"),2] <- "Plant lifespan (longevity)"  
  transl_t[which(transl_t[,1]%in%"X63"),2] <- "Stomata density"  
  transl_t[which(transl_t[,1]%in%"X66"),2] <- "Seed terminal velocity"  
  transl_t[which(transl_t[,1]%in%"X70"),2] <- "Litter nitrogen (N) content per litter dry mass"  
  transl_t[which(transl_t[,1]%in%"X77"),2] <- "Plant growth rate relative (plant relative growth rate, RGR)"  
  transl_t[which(transl_t[,1]%in%"X78"),2] <- "Leaf nitrogen (N) isotope signature (delta 15N)"  
  transl_t[which(transl_t[,1]%in%"X79"),2] <- "Leaf minus soil nitrogen (N) isotope signature (leaf delta 15N minus soil delta 15N)"  
  transl_t[which(transl_t[,1]%in%"X80"),2] <- "Root nitrogen (N) content per root dry mass"  
  transl_t[which(transl_t[,1]%in%"X82"),2] <- "Root tissue density (root dry mass per root volume)"  
  transl_t[which(transl_t[,1]%in%"X85"),2] <- "Leaf soluble components content per leaf dry mass"  
  transl_t[which(transl_t[,1]%in%"X87"),2] <- "Leaf lignin content per leaf dry mass"  
  transl_t[which(transl_t[,1]%in%"X92"),2] <- "Leaf cellulose content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X94"),2] <- "Leaf hemi-cellulose content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X95"),2] <- "Seed germination rate (germination efficiency)" 
  transl_t[which(transl_t[,1]%in%"X96"),2] <- "Seed oil content per seed mass" 
  transl_t[which(transl_t[,1]%in%"X97"),2] <- "Seed protein content per seed mass" 
  transl_t[which(transl_t[,1]%in%"X106"),2] <- "Stomata conductance per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X110"),2] <- "Plant biomass and allometry: Leaf dry mass per plant dry mass (leaf weight ratio, LWR)" 
  transl_t[which(transl_t[,1]%in%"X111"),2] <- "Leaf transpiration rate per leaf area" 
  transl_t[which(transl_t[,1]%in%"X125"),2] <- "Leaf area per leaf fresh mass (specific leaf area (SLA or 1/LMA) based on leaf fresh mass)" 
  transl_t[which(transl_t[,1]%in%"X128"),2] <- "Plant biomass and allometry: Stem dry mass per plant" 
  transl_t[which(transl_t[,1]%in%"X129"),2] <- "Plant biomass and allometry: Leaf dry mass per plant" 
  transl_t[which(transl_t[,1]%in%"X131"),2] <- "Plant biomass and allometry: Seed number per plant" 
  transl_t[which(transl_t[,1]%in%"X134"),2] <- "Leaf photosynthesis rate per leaf transpiration (photosynthetic water use effinciency: WUE)" 
  transl_t[which(transl_t[,1]%in%"X138"),2] <- "Seed number per reproducton unit" 
  transl_t[which(transl_t[,1]%in%"X142"),2] <- "Leaf perimeter" 
  transl_t[which(transl_t[,1]%in%"X143"),2] <- "Leaf petiole length" 
  transl_t[which(transl_t[,1]%in%"X144"),2] <- "Leaf length" 
  transl_t[which(transl_t[,1]%in%"X145"),2] <- "Leaf width" 
  transl_t[which(transl_t[,1]%in%"X146"),2] <- "Leaf carbon/nitrogen (C/N) ratio" # LeCN
  transl_t[which(transl_t[,1]%in%"X147"),2] <- "Leaf phenols content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X163"),2] <- "Leaf fresh mass"   
  transl_t[which(transl_t[,1]%in%"X169"),2] <- "Stem conduit density (vessels and tracheids)"   
  transl_t[which(transl_t[,1]%in%"X170"),2] <- "Stem conduit cross-sectional area (vessels and tracheids)" 
  transl_t[which(transl_t[,1]%in%"X172"),2] <- "Stem conduit lumen cross-sectional area (vessels and tracheids) per stem sapwood cross-sectional are" 
  transl_t[which(transl_t[,1]%in%"X185"),2] <- "Leaf photosynthesis carboxylation capacity (Vcmax) per leaf dry mass (Farquhar model)" 
  transl_t[which(transl_t[,1]%in%"X186"),2] <- "Leaf photosynthesis carboxylation capacity (Vcmax) per leaf area (Farquhar model)" 
  transl_t[which(transl_t[,1]%in%"X200"),2] <- "Species occurrence range: number of floristic zones" 
  transl_t[which(transl_t[,1]%in%"X221"),2] <- "Species genotype: chromosome base number" 
  transl_t[which(transl_t[,1]%in%"X223"),2] <- "Species genotype: chromosome number" 
  transl_t[which(transl_t[,1]%in%"X224"),2] <- "Species genotype: chromosome cDNA content" 
  transl_t[which(transl_t[,1]%in%"X233"),2] <- "Dispersal unit dry mass" 
  transl_t[which(transl_t[,1]%in%"X235"),2] <- "Dispersal unit thickness " 
  transl_t[which(transl_t[,1]%in%"X236"),2] <- "Dispersal unit width" 
  transl_t[which(transl_t[,1]%in%"X237"),2] <- "Dispersal unit length" 
  transl_t[which(transl_t[,1]%in%"X238"),2] <- "Seed thickness" 
  transl_t[which(transl_t[,1]%in%"X239"),2] <- "Seed width" 
  transl_t[which(transl_t[,1]%in%"X249"),2] <- "Leaf aluminium (Al) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X250"),2] <- "Leaf boron (B) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X251"),2] <- "Leaf barium (Ba) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X252"),2] <- "Leaf calcium (Ca) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X253"),2] <- "Leaf chlorophyll fluorescence" 
  transl_t[which(transl_t[,1]%in%"X254"),2] <- "Leaf chromium (Cr) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X255"),2] <- "Leaf copper (Cu) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X256"),2] <- "Leaf iron (Fe) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X257"),2] <- "Leaf magnesium (Mg) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X258"),2] <- "Leaf manganese (Mn) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X259"),2] <- "Leaf molybdenum (Mo) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X260"),2] <- "Leaf sodium (Na) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X261"),2] <- "Leaf nickel (Ni) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X262"),2] <- "Leaf sulfur (S) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X264"),2] <- "Leaf silicon (Si) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X265"),2] <- "Leaf strontium (Sr) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X266"),2] <- "Leaf titanium (Ti) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X268"),2] <- "Leaf zinc (Zn) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X269"),2] <- "Leaf photosynthesis electron transport capacity (Jmax) per leaf area (Farquhar model)" 
  transl_t[which(transl_t[,1]%in%"X270"),2] <- "Leaf photosynthesis electron transport capacity (Jmax) per leaf dry mass (Farquhar model)" 
  transl_t[which(transl_t[,1]%in%"X281"),2] <- "Stem conduit diameter (vessels, tracheids)" 
  transl_t[which(transl_t[,1]%in%"X282"),2] <- "Wood vessel element length; stem conduit (vessel and tracheids) element length" 
  transl_t[which(transl_t[,1]%in%"X289"),2] <- "Wood fiber lengths" 
  transl_t[which(transl_t[,1]%in%"X297"),2] <- "Wood rays per millimetre" 
  transl_t[which(transl_t[,1]%in%"X324"),2] <- "Crown (canopy) length: diameter along the longest axis" 
  transl_t[which(transl_t[,1]%in%"X325"),2] <- "Crown (canopy) width" 
  transl_t[which(transl_t[,1]%in%"X333"),2] <- "Leaf ash content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X336"),2] <- "Seed number per ramet" 
  transl_t[which(transl_t[,1]%in%"X339"),2] <- "Shoot nitrogen (N) content per shoot dry mass" 
  transl_t[which(transl_t[,1]%in%"X340"),2] <- "Shoot phosphorus (P) content per shoot dry mass" 
  transl_t[which(transl_t[,1]%in%"X351"),2] <- "Seed number per dispersal unit" 
  transl_t[which(transl_t[,1]%in%"X353"),2] <- "Seed germination temperature" 
  transl_t[which(transl_t[,1]%in%"X363"),2] <- "Plant biomass and allometry: Root dry mass per plant" 
  transl_t[which(transl_t[,1]%in%"X364"),2] <- "Plant height of lowest branch" 
  transl_t[which(transl_t[,1]%in%"X406"),2] <- "Stem nitrogen (N) content per stem dry mass" 
  transl_t[which(transl_t[,1]%in%"X407"),2] <- "Stem carbon (C) content per stem dry mass" 
  transl_t[which(transl_t[,1]%in%"X410"),2] <- "Leaf area per plant" 
  transl_t[which(transl_t[,1]%in%"X413"),2] <- "Leaf chlorophyll content per leaf area" 
  transl_t[which(transl_t[,1]%in%"X420"),2] <- "Wood: bars per vessel perforation plate" 
  transl_t[which(transl_t[,1]%in%"X449"),2] <- "Plant biomass and allometry: Branch dry mass (alive, dead) per plant" 
  transl_t[which(transl_t[,1]%in%"X511"),2] <- "Plant number of branches per tree" 
  transl_t[which(transl_t[,1]%in%"X514"),2] <- "Root respiration rate per root dry mass" 
  transl_t[which(transl_t[,1]%in%"X520"),2] <- "Stem respiration rate per stem surface area" 
  transl_t[which(transl_t[,1]%in%"X539"),2] <- "Leaf chlorine (Cl) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X540"),2] <- "Leaf scandium (Sc) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X542"),2] <- "Leaf bromine (Br) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X543"),2] <- "Leaf rubidium (Rb) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X546"),2] <- "Leaf antimony (Sb) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X547"),2] <- "Leaf caesium (Cs) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X548"),2] <- "Leaf lanthanum (La) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X549"),2] <- "Leaf cerium (Ce) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X551"),2] <- "Leaf samarium (Sm) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X552"),2] <- "Leaf europium (Eu) content per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X570"),2] <- "Leaf carbon (C) content per leaf area" 
  transl_t[which(transl_t[,1]%in%"X616"),2] <- "Stem phosphorus (P) content per stem dry mass" 
  transl_t[which(transl_t[,1]%in%"X753"),2] <- "Leaf chlorophyll fluorescence" 
  transl_t[which(transl_t[,1]%in%"X759"),2] <- "Leaflet number per leaf" 
  transl_t[which(transl_t[,1]%in%"X777"),2] <- "Leaf petiole fresh mass" 
  transl_t[which(transl_t[,1]%in%"X778"),2] <- "Leaf petiole dry mass" 
  transl_t[which(transl_t[,1]%in%"X779"),2] <- "Leaf petiole diameter" 
  transl_t[which(transl_t[,1]%in%"X784"),2] <- "unknown_trait" 
  transl_t[which(transl_t[,1]%in%"X861"),2] <- "Branch number of secondary branches at first branching" 
  transl_t[which(transl_t[,1]%in%"X862"),2] <- "Branch number per height along the shoot axis" 
  transl_t[which(transl_t[,1]%in%"X888"),2] <- "Cone (strobilus) dry mass" 
  transl_t[which(transl_t[,1]%in%"X939"),2] <- "Leaf isoprene emission rate per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X940"),2] <- "Leaf length excluding petiole (leaf lamina length)" 
  transl_t[which(transl_t[,1]%in%"X967"),2] <- "Leaf volatile organic carbon (VOC): monoterpene emission rate per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X968"),2] <- "Leaf nitrogen (N) fraction in ammonium (NH4+)" 
  transl_t[which(transl_t[,1]%in%"X969"),2] <- "Leaf nitrogen (N) fraction in N2" 
  transl_t[which(transl_t[,1]%in%"X970"),2] <- "Leaf nitrogen (N) fraction in nitrate (NO3-)" 
  transl_t[which(transl_t[,1]%in%"X973"),2] <- "Leaf petiole projected area" 
  transl_t[which(transl_t[,1]%in%"X978"),2] <- "Leaf shrinkage" 
  transl_t[which(transl_t[,1]%in%"X981"),2] <- "Leaf transpiration rate per leaf dry mass" 
  transl_t[which(transl_t[,1]%in%"X982"),2] <- "Leaf relative water content (leaf water content fresh / leaf water content saturated; RWC)" 
  transl_t[which(transl_t[,1]%in%"X984"),2] <- "Leaf water saturation deficit" 
  transl_t[which(transl_t[,1]%in%"X985"),2] <- "Leaflet length" 
  transl_t[which(transl_t[,1]%in%"X1011"),2] <- "Leaf petiole projected area per petiole dry mass (specific leaf area (SLA) of leaf petiole)" 
  transl_t[which(transl_t[,1]%in%"X1096"),2] <- "Wood (sapwood) specific conductivity (stem specific conductivity)" 
  transl_t[which(transl_t[,1]%in%"X1097"),2] <- "Wood (sapwood) water content" 
  transl_t[which(transl_t[,1]%in%"X1103"),2] <- "Seed number per flower" 
  transl_t[which(transl_t[,1]%in%"X1104"),2] <- "Seed number per inflorescence (total, fertile, infertile)" 
  transl_t[which(transl_t[,1]%in%"X1105"),2] <- "Seed number per square meter" 
  transl_t[which(transl_t[,1]%in%"X1106"),2] <- "Seed number per stem" 
  transl_t[which(transl_t[,1]%in%"X1111"),2] <- "Seedbank density" 
  transl_t[which(transl_t[,1]%in%"X1130"),2] <- "Species environmental indicator value according to Ellenberg: continentality" 
  transl_t[which(transl_t[,1]%in%"X1131"),2] <- "Species environmental indicator value according to Ellenberg: light" 
  transl_t[which(transl_t[,1]%in%"X1132"),2] <- "Species environmental indicator value according to Ellenberg: moisture" 
  transl_t[which(transl_t[,1]%in%"X1133"),2] <- "Species environmental indicator value according to Ellenberg: nitrogen" 
  transl_t[which(transl_t[,1]%in%"X1134"),2] <- "Species environmental indicator value according to Ellenberg: pH " 
  transl_t[which(transl_t[,1]%in%"X1135"),2] <- "Species environmental indicator value according to Ellenberg: salt tolerance" 
  transl_t[which(transl_t[,1]%in%"X1136"),2] <- "Species environmental indicator value according to Ellenberg: temperature" 
  transl_t[which(transl_t[,1]%in%"X1186"),2] <- "Shoot length to first flower" 
  transl_t[which(transl_t[,1]%in%"X1187"),2] <- "Stem longevity" 
  transl_t[which(transl_t[,1]%in%"X1200"),2] <- "Twig diameter" 
  transl_t[which(transl_t[,1]%in%"X1204"),2] <- "Stem dry mass per stem fresh volume (stem specific density, SSD, Wood density) Twigs and branches sm" 
  
  
  #------------------
  transl_c_sd[grep(transl_c_sd[,1],pattern = "PCA_sd_CLIMATE"),2] <- "climate_sd"
  transl_s_sd[grep(transl_c_sd[,1],pattern = "PCA_sd_SOIL"),2] <-  "soil_sd"
  
  # soil  

  transl_s[which(transl_s[,1]%in%"ORCDRC_M_sl1_1km_ll.tif"),2] <- "C_content" 
  transl_s[which(transl_s[,1]%in%"ORCDRC_M_sl2_1km_ll.tif"),2] <- "C_content_2" 
  transl_s[which(transl_s[,1]%in%"ORCDRC_M_sl3_1km_ll.tif"),2] <- "C_content_3" 
  transl_s[which(transl_s[,1]%in%"ORCDRC_M_sl4_1km_ll.tif"),2] <- "C_content_4" 
  transl_s[which(transl_s[,1]%in%"ORCDRC_M_sl5_1km_ll.tif"),2] <- "C_content_5" 
  transl_s[which(transl_s[,1]%in%"ORCDRC_M_sl6_1km_ll.tif"),2] <- "C_content_6" 
  transl_s[which(transl_s[,1]%in%"ORCDRC_M_sl7_1km_ll.tif"),2] <- "C_content_7" 
  
  transl_s[which(transl_s[,1]%in%"BLDFIE_M_sl1_1km_ll.tif"),2] <- "Density" 
  transl_s[which(transl_s[,1]%in%"BLDFIE_M_sl2_1km_ll.tif"),2] <- "Density_2" 
  transl_s[which(transl_s[,1]%in%"BLDFIE_M_sl3_1km_ll.tif"),2] <- "Density_3" 
  transl_s[which(transl_s[,1]%in%"BLDFIE_M_sl4_1km_ll.tif"),2] <- "Density_4" 
  transl_s[which(transl_s[,1]%in%"BLDFIE_M_sl5_1km_ll.tif"),2] <- "Density_5" 
  transl_s[which(transl_s[,1]%in%"BLDFIE_M_sl6_1km_ll.tif"),2] <- "Density_6" 
  transl_s[which(transl_s[,1]%in%"BLDFIE_M_sl7_1km_ll.tif"),2] <- "Density_7" 
  
  transl_s[which(transl_s[,1]%in%"AWCtS_M_sl1_1km_ll.tif"),2] <- "WaterSat" 
  transl_s[which(transl_s[,1]%in%"AWCtS_M_sl2_1km_ll.tif"),2] <- "WaterSat_2" 
  transl_s[which(transl_s[,1]%in%"AWCtS_M_sl3_1km_ll.tif"),2] <- "WaterSat_3" 
  transl_s[which(transl_s[,1]%in%"AWCtS_M_sl4_1km_ll.tif"),2] <- "WaterSat_4" 
  transl_s[which(transl_s[,1]%in%"AWCtS_M_sl5_1km_ll.tif"),2] <- "WaterSat_5" 
  transl_s[which(transl_s[,1]%in%"AWCtS_M_sl6_1km_ll.tif"),2] <- "WaterSat_6" 
  transl_s[which(transl_s[,1]%in%"AWCtS_M_sl7_1km_ll.tif"),2] <- "WaterSat_7" 
  
  transl_s[which(transl_s[,1]%in%"AWCh1_M_sl1_1km_ll.tif"),2] <- "WaterPot10" 
  transl_s[which(transl_s[,1]%in%"AWCh1_M_sl2_1km_ll.tif"),2] <- "WaterPot10_2" 
  transl_s[which(transl_s[,1]%in%"AWCh1_M_sl3_1km_ll.tif"),2] <- "WaterPot10_3" 
  transl_s[which(transl_s[,1]%in%"AWCh1_M_sl4_1km_ll.tif"),2] <- "WaterPot10_4" 
  transl_s[which(transl_s[,1]%in%"AWCh1_M_sl5_1km_ll.tif"),2] <- "WaterPot10_5" 
  transl_s[which(transl_s[,1]%in%"AWCh1_M_sl6_1km_ll.tif"),2] <- "WaterPot10_6" 
  transl_s[which(transl_s[,1]%in%"AWCh1_M_sl7_1km_ll.tif"),2] <- "WaterPot10_7" 
  
  transl_s[which(transl_s[,1]%in%"AWCh2_M_sl1_1km_ll.tif"),2] <- "WaterPot20" 
  transl_s[which(transl_s[,1]%in%"AWCh2_M_sl2_1km_ll.tif"),2] <- "WaterPot20_2" 
  transl_s[which(transl_s[,1]%in%"AWCh2_M_sl3_1km_ll.tif"),2] <- "WaterPot20_3" 
  transl_s[which(transl_s[,1]%in%"AWCh2_M_sl4_1km_ll.tif"),2] <- "WaterPot20_4" 
  transl_s[which(transl_s[,1]%in%"AWCh2_M_sl5_1km_ll.tif"),2] <- "WaterPot20_5" 
  transl_s[which(transl_s[,1]%in%"AWCh2_M_sl6_1km_ll.tif"),2] <- "WaterPot20_6" 
  transl_s[which(transl_s[,1]%in%"AWCh2_M_sl7_1km_ll.tif"),2] <- "WaterPot20_7" 
  
  transl_s[which(transl_s[,1]%in%"AWCh3_M_sl1_1km_ll.tif"),2] <- "WaterPot32" 
  transl_s[which(transl_s[,1]%in%"AWCh3_M_sl2_1km_ll.tif"),2] <- "WaterPot32_2" 
  transl_s[which(transl_s[,1]%in%"AWCh3_M_sl3_1km_ll.tif"),2] <- "WaterPot32_3" 
  transl_s[which(transl_s[,1]%in%"AWCh3_M_sl4_1km_ll.tif"),2] <- "WaterPot32_4" 
  transl_s[which(transl_s[,1]%in%"AWCh3_M_sl5_1km_ll.tif"),2] <- "WaterPot32_5" 
  transl_s[which(transl_s[,1]%in%"AWCh3_M_sl6_1km_ll.tif"),2] <- "WaterPot32_6" 
  transl_s[which(transl_s[,1]%in%"AWCh3_M_sl7_1km_ll.tif"),2] <- "WaterPot32_7" 
  
  
  transl_s[which(transl_s[,1]%in%"WWP_M_sl1_1km_ll.tif"),2] <- "WaterWilt" 
  transl_s[which(transl_s[,1]%in%"WWP_M_sl2_1km_ll.tif"),2] <- "WaterWilt_2" 
  transl_s[which(transl_s[,1]%in%"WWP_M_sl3_1km_ll.tif"),2] <- "WaterWilt_3" 
  transl_s[which(transl_s[,1]%in%"WWP_M_sl4_1km_ll.tif"),2] <- "WaterWilt_4" 
  transl_s[which(transl_s[,1]%in%"WWP_M_sl5_1km_ll.tif"),2] <- "WaterWilt_5" 
  transl_s[which(transl_s[,1]%in%"WWP_M_sl6_1km_ll.tif"),2] <- "WaterWilt_6" 
  transl_s[which(transl_s[,1]%in%"WWP_M_sl7_1km_ll.tif"),2] <- "WaterWilt_7" 
  
  transl_s[which(transl_s[,1]%in%"SNDPPT_M_sl1_1km_ll.tif"),2] <- "Sand" 
  transl_s[which(transl_s[,1]%in%"SNDPPT_M_sl2_1km_ll.tif"),2] <- "Sand_2" 
  transl_s[which(transl_s[,1]%in%"SNDPPT_M_sl3_1km_ll.tif"),2] <- "Sand_3" 
  transl_s[which(transl_s[,1]%in%"SNDPPT_M_sl4_1km_ll.tif"),2] <- "Sand_4" 
  transl_s[which(transl_s[,1]%in%"SNDPPT_M_sl5_1km_ll.tif"),2] <- "Sand_5" 
  transl_s[which(transl_s[,1]%in%"SNDPPT_M_sl6_1km_ll.tif"),2] <- "Sand_6" 
  transl_s[which(transl_s[,1]%in%"SNDPPT_M_sl7_1km_ll.tif"),2] <- "Sand_7" 
  
  transl_s[which(transl_s[,1]%in%"SLTPPT_M_sl1_1km_ll.tif"),2] <- "Silt" 
  transl_s[which(transl_s[,1]%in%"SLTPPT_M_sl2_1km_ll.tif"),2] <- "Silt_2" 
  transl_s[which(transl_s[,1]%in%"SLTPPT_M_sl3_1km_ll.tif"),2] <- "Silt_3" 
  transl_s[which(transl_s[,1]%in%"SLTPPT_M_sl4_1km_ll.tif"),2] <- "Silt_4" 
  transl_s[which(transl_s[,1]%in%"SLTPPT_M_sl5_1km_ll.tif"),2] <- "Silt_5" 
  transl_s[which(transl_s[,1]%in%"SLTPPT_M_sl6_1km_ll.tif"),2] <- "Silt_6" 
  transl_s[which(transl_s[,1]%in%"SLTPPT_M_sl7_1km_ll.tif"),2] <- "Silt_7" 
  

  transl_s[which(transl_s[,1]%in%"PHIKCL_M_sl1_1km_ll.tif"),2] <- "pH" 
  transl_s[which(transl_s[,1]%in%"PHIKCL_M_sl2_1km_ll.tif"),2] <- "pH_2"
  transl_s[which(transl_s[,1]%in%"PHIKCL_M_sl3_1km_ll.tif"),2] <- "pH_3" 
  transl_s[which(transl_s[,1]%in%"PHIKCL_M_sl4_1km_ll.tif"),2] <- "pH_4" 
  transl_s[which(transl_s[,1]%in%"PHIKCL_M_sl5_1km_ll.tif"),2] <- "pH_5" 
  transl_s[which(transl_s[,1]%in%"PHIKCL_M_sl6_1km_ll.tif"),2] <- "pH_6" 
  transl_s[which(transl_s[,1]%in%"PHIKCL_M_sl7_1km_ll.tif"),2] <- "pH_7" 

  transl_s[which(transl_s[,1]%in%"OCDENS_M_sl1_1km_ll.tif"),2] <- "C_density" 
  transl_s[which(transl_s[,1]%in%"OCDENS_M_sl2_1km_ll.tif"),2] <- "C_density_2" 
  transl_s[which(transl_s[,1]%in%"OCDENS_M_sl3_1km_ll.tif"),2] <- "C_density_3" 
  transl_s[which(transl_s[,1]%in%"OCDENS_M_sl4_1km_ll.tif"),2] <- "C_density_4" 
  transl_s[which(transl_s[,1]%in%"OCDENS_M_sl5_1km_ll.tif"),2] <- "C_density_5" 
  transl_s[which(transl_s[,1]%in%"OCDENS_M_sl6_1km_ll.tif"),2] <- "C_density_6" 
  transl_s[which(transl_s[,1]%in%"OCDENS_M_sl7_1km_ll.tif"),2] <- "C_density_7" 
  
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_sd1_1km_ll.tif"),2] <- "C_stock" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_sd2_1km_ll.tif"),2] <- "C_stock_2" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_sd3_1km_ll.tif"),2] <- "C_stock_3" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_sd4_1km_ll.tif"),2] <- "C_stock_4" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_sd5_1km_ll.tif"),2] <- "C_stock_5" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_sd6_1km_ll.tif"),2] <- "C_stock_6" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_sd7_1km_ll.tif"),2] <- "C_stock_7" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_30cm_1km_ll.tif"),2] <- "C_stocki_0.3m" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_100cm_1km_ll.tif"),2] <- "C_stocki_1m" 
  transl_s[which(transl_s[,1]%in%"OCSTHA_M_200cm_1km_ll.tif"),2] <- "C_stocki_2m" 
  
  transl_s[which(transl_s[,1]%in%"CRFVOL_M_sl1_1km_ll.tif"),2] <- "Gravel" 
  transl_s[which(transl_s[,1]%in%"CRFVOL_M_sl2_1km_ll.tif"),2] <- "Gravel_2" 
  transl_s[which(transl_s[,1]%in%"CRFVOL_M_sl3_1km_ll.tif"),2] <- "Gravel_3" 
  transl_s[which(transl_s[,1]%in%"CRFVOL_M_sl4_1km_ll.tif"),2] <- "Gravel_4" 
  transl_s[which(transl_s[,1]%in%"CRFVOL_M_sl5_1km_ll.tif"),2] <- "Gravel_5" 
  transl_s[which(transl_s[,1]%in%"CRFVOL_M_sl6_1km_ll.tif"),2] <- "Gravel_6" 
  transl_s[which(transl_s[,1]%in%"CRFVOL_M_sl7_1km_ll.tif"),2] <- "Gravel_7"
  
  transl_s[which(transl_s[,1]%in%"CLYPPT_M_sl1_1km_ll.tif"),2] <- "Clay" 
  transl_s[which(transl_s[,1]%in%"CLYPPT_M_sl2_1km_ll.tif"),2] <- "Clay_2" 
  transl_s[which(transl_s[,1]%in%"CLYPPT_M_sl3_1km_ll.tif"),2] <- "Clay_3" 
  transl_s[which(transl_s[,1]%in%"CLYPPT_M_sl4_1km_ll.tif"),2] <- "Clay_4" 
  transl_s[which(transl_s[,1]%in%"CLYPPT_M_sl5_1km_ll.tif"),2] <- "Clay_5" 
  transl_s[which(transl_s[,1]%in%"CLYPPT_M_sl6_1km_ll.tif"),2] <- "Clay_6" 
  transl_s[which(transl_s[,1]%in%"CLYPPT_M_sl7_1km_ll.tif"),2] <- "Clay_7" 
  
  transl_s[which(transl_s[,1]%in%"CECSOL_M_sl1_1km_ll.tif"),2] <- "CEC" 
  transl_s[which(transl_s[,1]%in%"CECSOL_M_sl2_1km_ll.tif"),2] <- "CEC_2" 
  transl_s[which(transl_s[,1]%in%"CECSOL_M_sl3_1km_ll.tif"),2] <- "CEC_3" 
  transl_s[which(transl_s[,1]%in%"CECSOL_M_sl4_1km_ll.tif"),2] <- "CEC_4" 
  transl_s[which(transl_s[,1]%in%"CECSOL_M_sl5_1km_ll.tif"),2] <- "CEC_5" 
  transl_s[which(transl_s[,1]%in%"CECSOL_M_sl6_1km_ll.tif"),2] <- "CEC_6" 
  transl_s[which(transl_s[,1]%in%"CECSOL_M_sl7_1km_ll.tif"),2] <- "CEC_7" 
  
 
#---------------
#  addition soil
#-------------
  
  
  transl_a[grep(transl_s[,2],pattern = "Density"),2] <- "soil_physics"
  transl_a[grep(transl_s[,2],pattern = "WaterWilt"),2] <- "soil_physics"
  transl_a[grep(transl_s[,2],pattern = "WaterPot"),2] <- "soil_physics"
  transl_a[grep(transl_s[,2],pattern = "WaterSat"),2] <- "soil_physics"
  transl_a[grep(transl_s[,2],pattern = "Silt"),2] <- "soil_physics"
  transl_a[grep(transl_s[,2],pattern = "Sand"),2] <- "soil_physics"
  transl_a[grep(transl_s[,2],pattern = "Clay"),2] <- "soil_physics"
  transl_a[grep(transl_s[,2],pattern = "Gravel"),2] <- "soil_physics"  
  
  transl_a[grep(transl_s[,2],pattern = "pH"),2] <- "soil_chemistry"
  transl_a[grep(transl_s[,2],pattern = "CEC"),2] <- "soil_chemistry"
  transl_a[grep(transl_s[,2],pattern = "C_content"),2] <- "soil_chemistry"
  transl_a[grep(transl_s[,2],pattern = "Cdensity"),2] <- "soil_chemistry"
  transl_a[grep(transl_s[,2],pattern = "C_stock"),2] <- "soil_chemistry"

  length(transl_a[!is.na(transl_a[,2]),2])==length(transl_s[!is.na(transl_s[,2]),2])

  #-----------
  # CLIMATE
  #-----------
  transl_c[which(transl_c[,1]%in%"wind.sd.nc"),2] <- "Wind_sd" 
  transl_c[which(transl_c[,1]%in%"wind.max.nc"),2] <- "Wind_max" 
  transl_c[which(transl_c[,1]%in%"wind.min.nc"),2] <- "Wind_min" 
  transl_c[which(transl_c[,1]%in%"wind.mean.nc"),2] <- "Wind" 
  transl_c[which(transl_c[,1]%in%"srad.sd.nc"),2] <- "Solar rad_sd" 
  transl_c[which(transl_c[,1]%in%"srad.max.nc"),2] <- "Solar rad_max" 
  transl_c[which(transl_c[,1]%in%"srad.min.nc"),2] <- "Solar rad_min" 
  transl_c[which(transl_c[,1]%in%"srad.mean.nc"),2] <- "Solar rad" 
  transl_c[which(transl_c[,1]%in%"vapr.sd.nc"),2] <- "Vapour pressure_sd" 
  transl_c[which(transl_c[,1]%in%"vapr.max.nc"),2] <- "Vapour pressure_max" 
  transl_c[which(transl_c[,1]%in%"vapr.min.nc"),2] <- "Vapour pressure_min" 
  transl_c[which(transl_c[,1]%in%"vapr.mean.nc"),2] <- "Vapour pressure" 
  transl_c[which(transl_c[,1]%in%"PrecipitationSeasonality.nc"),2] <- "Precipitation_sd" 
  transl_c[which(transl_c[,1]%in%"PrecipitationofDriestMonth.nc"),2] <- "Precipitation_min" 
  transl_c[which(transl_c[,1]%in%"PrecipitationofWettestMonth.nc"),2] <- "Precipitation_max" 
  transl_c[which(transl_c[,1]%in%"AnnualPrecipitation.nc"),2] <- "Precipitation" 
  transl_c[which(transl_c[,1]%in%"MeanDiurnalRange.nc"),2] <- "Temp_d" 
  transl_c[which(transl_c[,1]%in%"TemperatureSeasonality.nc"),2] <- "Temp_sd" 
  transl_c[which(transl_c[,1]%in%"MinTemperatureofColdestMonth.nc"),2] <- "Temp_min" 
  transl_c[which(transl_c[,1]%in%"MaxTemperatureofWarmestMonth.nc"),2] <- "Temp_max" 
  transl_c[which(transl_c[,1]%in%"AnnualMeanTemperature.nc"),2] <- "Temp" 

  #------------------
  # climate sd
  #------------------
  transl_c_sd[which(transl_c_sd[,1]%in%"PCA_sd_CLIMATE"),2] <- "climate_sd"
  transl_s_sd[which(transl_s_sd[,1]%in%"PCA_sd_SOIL"),2] <-  "soil_sd"
    
  #------------------
  #additions
  #------------------
  # transl_a[which(transl_a[,1]%in%"srad.sd.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"srad.max.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"srad.min.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"srad.mean.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"MeanDiurnalRange.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"TemperatureSeasonality.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"MinTemperatureofColdestMonth.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"MaxTemperatureofWarmestMonth.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"AnnualMeanTemperature.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"wind.sd.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"wind.max.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"wind.min.nc"),2] <- "energy" 
  # transl_a[which(transl_a[,1]%in%"wind.mean.nc"),2] <- "energy" 
  # 
  # transl_a[which(transl_a[,1]%in%"vapr.sd.nc"),2] <- "climate_water" 
  # transl_a[which(transl_a[,1]%in%"vapr.max.nc"),2] <- "climate_water" 
  # transl_a[which(transl_a[,1]%in%"vapr.min.nc"),2] <- "climate_water" 
  # transl_a[which(transl_a[,1]%in%"vapr.mean.nc"),2] <- "climate_water" 
  # transl_a[which(transl_a[,1]%in%"PrecipitationSeasonality.nc"),2] <- "climate_water" 
  # transl_a[which(transl_a[,1]%in%"PrecipitationofDriestMonth.nc"),2] <- "climate_water" 
  # transl_a[which(transl_a[,1]%in%"PrecipitationofWettestMonth.nc"),2] <- "climate_water" 
  # transl_a[which(transl_a[,1]%in%"AnnualPrecipitation.nc"),2] <- "climate_water" 
  
  
  transl_a[which(transl_a[,1]%in%"srad.sd.nc"),2] <- "variability" 
  transl_a[which(transl_a[,1]%in%"srad.max.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"srad.min.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"srad.mean.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"MeanDiurnalRange.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"TemperatureSeasonality.nc"),2] <- "variability" 
  transl_a[which(transl_a[,1]%in%"MinTemperatureofColdestMonth.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"MaxTemperatureofWarmestMonth.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"AnnualMeanTemperature.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"wind.sd.nc"),2] <- "variability" 
  transl_a[which(transl_a[,1]%in%"wind.max.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"wind.min.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"wind.mean.nc"),2] <- "minmaxmean" 
  
  transl_a[which(transl_a[,1]%in%"vapr.sd.nc"),2] <- "variability" 
  transl_a[which(transl_a[,1]%in%"vapr.max.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"vapr.min.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"vapr.mean.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"PrecipitationSeasonality.nc"),2] <- "variability" 
  transl_a[which(transl_a[,1]%in%"PrecipitationofDriestMonth.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"PrecipitationofWettestMonth.nc"),2] <- "minmaxmean" 
  transl_a[which(transl_a[,1]%in%"AnnualPrecipitation.nc"),2] <- "minmaxmean" 
  #----------------------------------------------------
  
  transl_a1[which(transl_a1[,1]%in%"srad.sd.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"srad.max.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"srad.min.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"srad.mean.nc"),2] <- "mean" 
  transl_a1[which(transl_a1[,1]%in%"MeanDiurnalRange.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"TemperatureSeasonality.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"MinTemperatureofColdestMonth.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"MaxTemperatureofWarmestMonth.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"AnnualMeanTemperature.nc"),2] <- "mean" 
  transl_a1[which(transl_a1[,1]%in%"wind.sd.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"wind.max.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"wind.min.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"wind.mean.nc"),2] <- "mean" 
  
  transl_a1[which(transl_a1[,1]%in%"vapr.sd.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"vapr.max.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"vapr.min.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"vapr.mean.nc"),2] <- "mean" 
  transl_a1[which(transl_a1[,1]%in%"PrecipitationSeasonality.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"PrecipitationofDriestMonth.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"PrecipitationofWettestMonth.nc"),2] <- "varouter" 
  transl_a1[which(transl_a1[,1]%in%"AnnualPrecipitation.nc"),2] <- "mean" 
  #----------------------------------------------------
  #alternative:
  transl_a2[which(transl_a2[,1]%in%"srad.sd.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"srad.max.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"srad.min.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"srad.mean.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"MeanDiurnalRange.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"TemperatureSeasonality.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"MinTemperatureofColdestMonth.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"MaxTemperatureofWarmestMonth.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"AnnualMeanTemperature.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"wind.sd.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"wind.max.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"wind.min.nc"),2] <- "climate_energy" 
  transl_a2[which(transl_a2[,1]%in%"wind.mean.nc"),2] <- "climate_energy" 
  
  transl_a2[which(transl_a2[,1]%in%"vapr.sd.nc"),2] <- "climate_water" 
  transl_a2[which(transl_a2[,1]%in%"vapr.max.nc"),2] <- "climate_water" 
  transl_a2[which(transl_a2[,1]%in%"vapr.min.nc"),2] <- "climate_water" 
  transl_a2[which(transl_a2[,1]%in%"vapr.mean.nc"),2] <- "climate_water" 
  transl_a2[which(transl_a2[,1]%in%"PrecipitationSeasonality.nc"),2] <- "climate_water" 
  transl_a2[which(transl_a2[,1]%in%"PrecipitationofDriestMonth.nc"),2] <- "climate_water" 
  transl_a2[which(transl_a2[,1]%in%"PrecipitationofWettestMonth.nc"),2] <- "climate_water" 
  transl_a2[which(transl_a2[,1]%in%"AnnualPrecipitation.nc"),2] <- "climate_water" 
  #----------------------------------------------------
  #alternative:
  transl_a3[which(transl_a3[,1]%in%"srad.sd.nc"),2] <- "climate_A1" 
  transl_a3[which(transl_a3[,1]%in%"srad.min.nc"),2] <- "climate_A1" 
  transl_a3[which(transl_a3[,1]%in%"MinTemperatureofColdestMonth.nc"),2] <- "climate_A1" 
  transl_a3[which(transl_a3[,1]%in%"AnnualMeanTemperature.nc"),2] <- "climate_A1" 
  transl_a3[which(transl_a3[,1]%in%"vapr.max.nc"),2] <- "climate_A1" 
  transl_a3[which(transl_a3[,1]%in%"vapr.min.nc"),2] <- "climate_A1" 
  transl_a3[which(transl_a3[,1]%in%"vapr.mean.nc"),2] <- "climate_A1" 
  transl_a3[which(transl_a3[,1]%in%"PrecipitationofWettestMonth.nc"),2] <- "climate_A1" 
  transl_a3[which(transl_a3[,1]%in%"AnnualPrecipitation.nc"),2] <- "climate_A1" 
  
  transl_a3[which(transl_a3[,1]%in%"srad.max.nc"),2] <- "climate_A2" 
  transl_a3[which(transl_a3[,1]%in%"srad.mean.nc"),2] <- "climate_A2" 
  transl_a3[which(transl_a3[,1]%in%"MeanDiurnalRange.nc"),2] <- "climate_A2" 
  transl_a3[which(transl_a3[,1]%in%"TemperatureSeasonality.nc"),2] <- "climate_A2" 
  transl_a3[which(transl_a3[,1]%in%"MaxTemperatureofWarmestMonth.nc"),2] <- "climate_A2" 
  transl_a3[which(transl_a3[,1]%in%"PrecipitationSeasonality.nc"),2] <- "climate_A2" 
  transl_a3[which(transl_a3[,1]%in%"PrecipitationofDriestMonth.nc"),2] <- "climate_A2" 
  
  transl_a3[which(transl_a3[,1]%in%"wind.sd.nc"),2] <- "climate_A3" 
  transl_a3[which(transl_a3[,1]%in%"wind.max.nc"),2] <- "climate_A3" 
  transl_a3[which(transl_a3[,1]%in%"wind.min.nc"),2] <- "climate_A3" 
  transl_a3[which(transl_a3[,1]%in%"wind.mean.nc"),2] <- "climate_A3" 
  transl_a3[which(transl_a3[,1]%in%"vapr.sd.nc"),2] <- "climate_A3" 
  

  #--------------------------------------------------------------------------------------
  transl_t_sd[grep(transl_t_sd[,1],pattern = "sd.unique_spec"),2] <- "trait_sd" 
  
  vec <- rep("other",nrow(transl_s));
  vec[!is.na(transl_c[,2])] <- "climate"
  vec[!is.na(transl_s[,2])] <- "soil"
  vec[!is.na(transl_t[,2])] <- "trait"
  vec[!is.na(transl_t_sd[,2])] <- "trait_sd"
  vec[!is.na(transl_s_sd[,2])] <- "soil_sd"
  vec[!is.na(transl_c_sd[,2])] <- "climate_sd"
  vec2 <- rep("other",nrow(transl_s));
  vec2[!is.na(transl_c[,2])] <- transl_c[!is.na(transl_c[,2]),2]
  vec2[!is.na(transl_s[,2])] <- transl_s[!is.na(transl_s[,2]),2]
  vec2[!is.na(transl_t[,2])] <- transl_t[!is.na(transl_t[,2]),2]
  vec3 <- rep("other",nrow(transl_s));
  vec3[!is.na(transl_a[,2])] <- transl_a[!is.na(transl_a[,2]),2]
  vec4 <- rep("other",nrow(transl_d));
  vec4[!is.na(transl_d[,2])] <- transl_d[!is.na(transl_d[,2]),2]

  vec5 <- rep("other",nrow(transl_a1));
  vec5[!is.na(transl_a1[,2])] <- transl_a1[!is.na(transl_a1[,2]),2]
  vec6 <- rep("other",nrow(transl_a2));
  vec6[!is.na(transl_a2[,2])] <- transl_a2[!is.na(transl_a2[,2]),2]
  vec7 <- rep("other",nrow(transl_a3));
  vec7[!is.na(transl_a3[,2])] <- transl_a3[!is.na(transl_a2[,2]),2]
  
  out <- cbind(input,vec,vec2,vec3,vec4,vec5,vec6,vec7)
  
#  out <- list(climate = transl_c,
#              soil=transl_s,
#              traits=transl_t)
 
  return(out)
}

